0:
  Direction: down
  Event Flag: 0
  Movement: 10
  Show Sprite: when event flag unset
  Sprite: 1
  Text Pointer 1: $0
  Text Pointer 2: $0
  Type: person
1:
  Direction: down
  Event Flag: 0
  Movement: 606
  Show Sprite: always
  Sprite: 52
  Text Pointer 1: The_World_Of_Emile.debug
  Text Pointer 2: $0
  Type: person
2:
  Direction: down
  Event Flag: 0
  Movement: 10
  Show Sprite: always
  Sprite: 52
  Text Pointer 1: The_World_Of_Emile.prince_fluff
  Text Pointer 2: $0
  Type: person
3:
  Direction: down
  Event Flag: 0
  Movement: 12
  Show Sprite: always
  Sprite: 44
  Text Pointer 1: The_World_Of_Emile.debug
  Text Pointer 2: $0
  Type: person
